// <auto-generated />
using CRUD_DOTNET6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD_DOTNET6.Migrations
{
    [DbContext(typeof(CRUD_DOTNET6Context))]
    [Migration("20220819105515_AlterExaminePersonSeedData")]
    partial class AlterExaminePersonSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD_DOTNET6.Models.ExaminePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactDetails");

                    b.Property<string>("Feedback");

                    b.Property<string>("Name");

                    b.Property<string>("Oraganization");

                    b.HasKey("Id");

                    b.ToTable("ExaminePerson");

                    b.HasData(
                        new { Id = 1, ContactDetails = "32568.1254.3325", Feedback = "UX Part of app is good.", Name = "Rahul Sharma", Oraganization = "ABC University" },
                        new { Id = 2, ContactDetails = "235657.2365.3258", Feedback = "Works well with CRUD Operations.", Name = "Vivek Lambha", Oraganization = "XYZ Solutions" },
                        new { Id = 3, ContactDetails = "32546.4569.2245", Feedback = "This Web App Works Good.", Name = "Ayush Srivastava", Oraganization = "PQR Pvt. L." },
                        new { Id = 4, ContactDetails = "65489.2315.4658", Feedback = "Love This App.", Name = "Vijay Singh", Oraganization = "JIT" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
