// <auto-generated />
using CRUD_DOTNET6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD_DOTNET6.Migrations
{
    [DbContext(typeof(CRUD_DOTNET6Context))]
    [Migration("20220819104900_SeedExaminePersonTable")]
    partial class SeedExaminePersonTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD_DOTNET6.Models.ExaminePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactDetails");

                    b.Property<string>("Feedback");

                    b.Property<string>("Name");

                    b.Property<string>("Oraganization");

                    b.HasKey("Id");

                    b.ToTable("ExaminePerson");

                    b.HasData(
                        new { Id = 1, ContactDetails = "32568.1254.3325", Feedback = "UX Part of app is good.", Name = "Rahul Sharma", Oraganization = "ABC University" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
